package xyz.froud.jvisa.constants;

import xyz.froud.jvisa.JVisaLibrary;

import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Status codes that VISA driver-level operations can return
 *
 * @see <a href="https://pyvisa.readthedocs.io/en/latest/api/constants.html#pyvisa.constants.StatusCode">Class <code>StatusCode</code> in PyVISA</a>
 */
public enum StatusCode {
    ERROR_ABORT(JVisaLibrary.VI_ERROR_ABORT),
    ERROR_ATTRIBUTE_READ_ONLY(JVisaLibrary.VI_ERROR_ATTR_READONLY),
    ERROR_BUS_ERROR(JVisaLibrary.VI_ERROR_BERR),
    ERROR_CLOSING_FAILED(JVisaLibrary.VI_ERROR_CLOSING_FAILED),
    ERROR_CONNECTION_LOST(JVisaLibrary.VI_ERROR_CONN_LOST),
    ERROR_FILE_ACCESS(JVisaLibrary.VI_ERROR_FILE_ACCESS),
    ERROR_FILE_I_O(JVisaLibrary.VI_ERROR_FILE_IO),
    ERROR_HANDLER_NOT_INSTALLED(JVisaLibrary.VI_ERROR_HNDLR_NINSTALLED),
    ERROR_IN_PROGRESS(JVisaLibrary.VI_ERROR_IN_PROGRESS),
    ERROR_INPUT_PROTOCOL_VIOLATION(JVisaLibrary.VI_ERROR_INP_PROT_VIOL),
    ERROR_INTERFACE_NUMBER_NOT_CONFIGURED(JVisaLibrary.VI_ERROR_INTF_NUM_NCONFIG),
    ERROR_INTERRUPT_PENDING(JVisaLibrary.VI_ERROR_INTR_PENDING),
    ERROR_INVALID_ACCESS_KEY(JVisaLibrary.VI_ERROR_INV_ACCESS_KEY),
    ERROR_INVALID_ACCESS_MODE(JVisaLibrary.VI_ERROR_INV_ACC_MODE),
    ERROR_INVALID_ADDRESS_SPACE(JVisaLibrary.VI_ERROR_INV_SPACE),
    ERROR_INVALID_CONTEXT(JVisaLibrary.VI_ERROR_INV_CONTEXT),
    ERROR_INVALID_DEGREE(JVisaLibrary.VI_ERROR_INV_DEGREE),
    ERROR_INVALID_EVENT(JVisaLibrary.VI_ERROR_INV_EVENT),
    ERROR_INVALID_EXPRESSION(JVisaLibrary.VI_ERROR_INV_EXPR),
    ERROR_INVALID_FORMAT(JVisaLibrary.VI_ERROR_INV_FMT),
    ERROR_INVALID_HANDLER_REFERENCE(JVisaLibrary.VI_ERROR_INV_HNDLR_REF),
    ERROR_INVALID_JOB_I_D(JVisaLibrary.VI_ERROR_INV_JOB_ID),
    ERROR_INVALID_LENGTH(JVisaLibrary.VI_ERROR_INV_LENGTH),
    ERROR_INVALID_LINE(JVisaLibrary.VI_ERROR_INV_LINE),
    ERROR_INVALID_LOCK_TYPE(JVisaLibrary.VI_ERROR_INV_LOCK_TYPE),
    ERROR_INVALID_MASK(JVisaLibrary.VI_ERROR_INV_MASK),
    ERROR_INVALID_MECHANISM(JVisaLibrary.VI_ERROR_INV_MECH),
    ERROR_INVALID_MODE(JVisaLibrary.VI_ERROR_INV_MODE),
    ERROR_INVALID_OBJECT(JVisaLibrary.VI_ERROR_INV_OBJECT),
    ERROR_INVALID_OFFSET(JVisaLibrary.VI_ERROR_INV_OFFSET),
    ERROR_INVALID_PARAMETER(JVisaLibrary.VI_ERROR_INV_PARAMETER),
    ERROR_INVALID_PROTOCOL(JVisaLibrary.VI_ERROR_INV_PROT),
    ERROR_INVALID_RESOURCE_NAME(JVisaLibrary.VI_ERROR_INV_RSRC_NAME),
    ERROR_INVALID_SETUP(JVisaLibrary.VI_ERROR_INV_SETUP),
    ERROR_INVALID_SIZE(JVisaLibrary.VI_ERROR_INV_SIZE),
    ERROR_INVALID_WIDTH(JVisaLibrary.VI_ERROR_INV_WIDTH),
    ERROR_IO(JVisaLibrary.VI_ERROR_IO),
    ERROR_LIBRARY_NOT_FOUND(JVisaLibrary.VI_ERROR_LIBRARY_NFOUND),
    ERROR_LINE_IN_USE(JVisaLibrary.VI_ERROR_LINE_IN_USE),
    ERROR_MACHINE_NOT_AVAILABLE(-1073807193),
    ERROR_MEMORY_NOT_SHARED(JVisaLibrary.VI_ERROR_MEM_NSHARED),
    ERROR_NO_LISTENERS(JVisaLibrary.VI_ERROR_NLISTENERS),
    ERROR_NONIMPLEMENTED_OPERATION(JVisaLibrary.VI_ERROR_NIMPL_OPER),
    ERROR_NONSUPPORTED_ATTRIBUTE(JVisaLibrary.VI_ERROR_NSUP_ATTR),
    ERROR_NONSUPPORTED_ATTRIBUTE_STATE(JVisaLibrary.VI_ERROR_NSUP_ATTR_STATE),
    ERROR_NONSUPPORTED_FORMAT(JVisaLibrary.VI_ERROR_NSUP_FMT),
    ERROR_NONSUPPORTED_INTERRUPT(JVisaLibrary.VI_ERROR_NSUP_INTR),
    ERROR_NONSUPPORTED_LINE(JVisaLibrary.VI_ERROR_NSUP_LINE),
    ERROR_NONSUPPORTED_MECHANISM(JVisaLibrary.VI_ERROR_NSUP_MECH),
    ERROR_NONSUPPORTED_MODE(JVisaLibrary.VI_ERROR_NSUP_MODE),
    ERROR_NONSUPPORTED_OFFSET(JVisaLibrary.VI_ERROR_NSUP_OFFSET),
    ERROR_NONSUPPORTED_OFFSET_ALIGNMENT(JVisaLibrary.VI_ERROR_NSUP_ALIGN_OFFSET),
    ERROR_NONSUPPORTED_OPERATION(JVisaLibrary.VI_ERROR_NSUP_OPER),
    ERROR_NONSUPPORTED_VARYING_WIDTHS(JVisaLibrary.VI_ERROR_NSUP_VAR_WIDTH),
    ERROR_NONSUPPORTED_WIDTH(JVisaLibrary.VI_ERROR_NSUP_WIDTH),
    ERROR_NO_PERMISSION(JVisaLibrary.VI_ERROR_NPERMISSION),
    ERROR_NOT_CIC(JVisaLibrary.VI_ERROR_NCIC),
    ERROR_NOT_ENABLED(JVisaLibrary.VI_ERROR_NENABLED),
    ERROR_NOT_SYSTEM_CONTROLLER(JVisaLibrary.VI_ERROR_NSYS_CNTLR),
    ERROR_OUTPUT_PROTOCOL_VIOLATION(JVisaLibrary.VI_ERROR_OUTP_PROT_VIOL),
    ERROR_QUEUE_ERROR(JVisaLibrary.VI_ERROR_QUEUE_ERROR),
    ERROR_QUEUE_OVERFLOW(-1073807315),
    ERROR_RAW_READ_PROTOCOL_VIOLATION(JVisaLibrary.VI_ERROR_RAW_RD_PROT_VIOL),
    ERROR_RAW_WRITE_PROTOCOL_VIOLATION(JVisaLibrary.VI_ERROR_RAW_WR_PROT_VIOL),
    ERROR_RESOURCE_BUSY(JVisaLibrary.VI_ERROR_RSRC_BUSY),
    ERROR_RESOURCE_LOCKED(JVisaLibrary.VI_ERROR_RSRC_LOCKED),
    ERROR_RESOURCE_NOT_FOUND(JVisaLibrary.VI_ERROR_RSRC_NFOUND),
    ERROR_RESPONSE_PENDING(JVisaLibrary.VI_ERROR_RESP_PENDING),
    ERROR_SERIAL_FRAMING(JVisaLibrary.VI_ERROR_ASRL_FRAMING),
    ERROR_SERIAL_OVERRUN(JVisaLibrary.VI_ERROR_ASRL_OVERRUN),
    ERROR_SERIAL_PARITY(JVisaLibrary.VI_ERROR_ASRL_PARITY),
    ERROR_SESSION_NOT_LOCKED(JVisaLibrary.VI_ERROR_SESN_NLOCKED),
    ERROR_SRQ_NOT_OCCURRED(JVisaLibrary.VI_ERROR_SRQ_NOCCURRED),
    ERROR_SYSTEM_ERROR(JVisaLibrary.VI_ERROR_SYSTEM_ERROR),
    ERROR_TIMEOUT(JVisaLibrary.VI_ERROR_TMO),
    ERROR_TRIGGER_NOT_MAPPED(JVisaLibrary.VI_ERROR_TRIG_NMAPPED),
    ERROR_USER_BUFFER(JVisaLibrary.VI_ERROR_USER_BUF),
    ERROR_WINDOW_ALREADY_MAPPED(JVisaLibrary.VI_ERROR_WINDOW_MAPPED),
    ERROR_WINDOW_NOT_MAPPED(JVisaLibrary.VI_ERROR_WINDOW_NMAPPED),
    SUCCESS(0),
    SUCCESS_DEVICE_NOT_PRESENT(JVisaLibrary.VI_SUCCESS_DEV_NPRESENT),
    SUCCESS_EVENT_ALREADY_DISABLED(JVisaLibrary.VI_SUCCESS_EVENT_DIS),
    SUCCESS_EVENT_ALREADY_ENABLED(JVisaLibrary.VI_SUCCESS_EVENT_EN),
    SUCCESS_MAX_COUNT_READ(JVisaLibrary.VI_SUCCESS_MAX_CNT),
    SUCCESS_NESTED_EXCLUSIVE(JVisaLibrary.VI_SUCCESS_NESTED_EXCLUSIVE),
    SUCCESS_NESTED_SHARED(JVisaLibrary.VI_SUCCESS_NESTED_SHARED),
    SUCCESS_NO_MORE_HANDLER_CALLS_IN_CHAIN(JVisaLibrary.VI_SUCCESS_NCHAIN),
    SUCCESS_QUEUE_ALREADY_EMPTY(JVisaLibrary.VI_SUCCESS_QUEUE_EMPTY),
    SUCCESS_QUEUE_NOT_EMPTY(JVisaLibrary.VI_SUCCESS_QUEUE_NEMPTY),
    SUCCESS_SYNCHRONOUS(JVisaLibrary.VI_SUCCESS_SYNC),
    SUCCESS_TERMINATION_CHARACTER_READ(JVisaLibrary.VI_SUCCESS_TERM_CHAR),
    SUCCESS_TRIGGER_ALREADY_MAPPED(JVisaLibrary.VI_SUCCESS_TRIG_MAPPED),
    WARNING_CONFIGURATION_NOT_LOADED(JVisaLibrary.VI_WARN_CONFIG_NLOADED),
    WARNING_EXT_FUNCTION_NOT_IMPLEMENTED(JVisaLibrary.VI_WARN_EXT_FUNC_NIMPL),
    WARNING_NONSUPPORTED_ATTRIBUTE_STATE(JVisaLibrary.VI_WARN_NSUP_ATTR_STATE),
    WARNING_NONSUPPORTED_BUFFER(JVisaLibrary.VI_WARN_NSUP_BUF),
    WARNING_NULL_OBJECT(JVisaLibrary.VI_WARN_NULL_OBJECT),
    WANING_QUEUE_OVERFLOW(JVisaLibrary.VI_WARN_QUEUE_OVERFLOW),
    WARNING_UNKNOWN_STATUS(JVisaLibrary.VI_WARN_UNKNOWN_STATUS);

    public final long VALUE;

    StatusCode(long value) {
        this.VALUE = value;
    }

    private static final Map<Long, StatusCode> VALUE_MAP
            = Stream.of(StatusCode.values())
            .collect(Collectors.toMap(e -> e.VALUE, e -> e));

    public static StatusCode parseLong(long value) {
        return VALUE_MAP.get(value);
    }
}
